name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Necesitamos permisos explícitos porque el GITHUB_TOKEN tiene permisos por defecto en lectura.
# Esto permite crear releases y subir assets desde el workflow.
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B -DskipTests clean package
      - name: List target directory
        run: ls -la target || dir target
      - name: Find built jar
        id: find_jar
        run: |
          set -e
          echo "Looking for Juledtoys jar in target/"
          JAR=$(ls target/Juledtoys-*.jar 2>/dev/null | head -n 1 || true)
          if [ -z "$JAR" ]; then
            echo "No Juledtoys jar found in target/"
            exit 1
          fi
          echo "Found jar: $JAR"
          echo "jar=$JAR" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload jar to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_jar.outputs.jar }}
          asset_name: Juledtoys-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
